version: "3"
services:
  site-a:
    image: nginx
    restart: always
    networks:
      - reverse-proxy
    environment:
      - VIRTUAL_HOST=c.designsos.org
      - LETSENCRYPT_HOST=c.designsos.org
      - LETSENCRYPT_EMAIL=hillarywando@gmail.com
  site-b:
    image: nginx
    restart: always
    networks:
      - reverse-proxy
    environment:
      - VIRTUAL_HOST=d.designsos.org
      - LETSENCRYPT_HOST=d.designsos.org
      - LETSENCRYPT_EMAIL=hillarywando@gmail.com
networks:
  reverse-proxy:
    external:
      name: reverse-proxy